FROM node:20-slim

WORKDIR /app

# Evita Husky/prepare scripts
ENV HUSKY=0
ENV NPM_CONFIG_IGNORE_SCRIPTS=true

# Instala dependências
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

# Copia código (mas será sobrescrito via volume)
COPY frontend .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
