"""create ibov_history table

Revision ID: 1e75643b289f
Revises: 81d92d0b79d3
Create Date: 2025-12-11 12:29:30.644348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e75643b289f'
down_revision: Union[str, Sequence[str], None] = '81d92d0b79d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibov_history',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('trade_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibov_history')
    # ### end Alembic commands ###
