"""Add balancing_settings to users

Revision ID: 2e82086b5fe9
Revises: 705ae752d65e
Create Date: 2025-12-27 18:36:55.461449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e82086b5fe9'
down_revision: Union[str, Sequence[str], None] = '705ae752d65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balancing_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balancing_settings')
    # ### end Alembic commands ###
