"""create asset_purchases table

Revision ID: 3a4bdcf67ec9
Revises: 1e75643b289f
Create Date: 2025-12-11 19:37:07.192758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4bdcf67ec9'
down_revision: Union[str, Sequence[str], None] = '1e75643b289f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_purchases_id'), 'asset_purchases', ['id'], unique=False)
    op.create_index(op.f('ix_asset_purchases_ticker'), 'asset_purchases', ['ticker'], unique=False)
    op.create_index(op.f('ix_asset_purchases_user_id'), 'asset_purchases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_purchases_user_id'), table_name='asset_purchases')
    op.drop_index(op.f('ix_asset_purchases_ticker'), table_name='asset_purchases')
    op.drop_index(op.f('ix_asset_purchases_id'), table_name='asset_purchases')
    op.drop_table('asset_purchases')
    # ### end Alembic commands ###
