"""create cdi_history table

Revision ID: 81d92d0b79d3
Revises: df33b7617cc2
Create Date: 2025-12-10 15:04:37.534916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d92d0b79d3'
down_revision: Union[str, Sequence[str], None] = 'df33b7617cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdi_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date')
    )
    op.create_index(op.f('ix_cdi_history_id'), 'cdi_history', ['id'], unique=False)
    op.add_column('b3_prices', sa.Column('market_type', sa.Integer(), nullable=True))
    op.drop_index(op.f('b3_prices_ticker_trade_date_idx'), table_name='b3_prices')
    op.drop_index(op.f('b3_prices_ticker_trade_date_uniq'), table_name='b3_prices')
    op.drop_index(op.f('idx_b3_prices_ticker'), table_name='b3_prices')
    op.create_index(op.f('ix_b3_prices_id'), 'b3_prices', ['id'], unique=False)
    op.create_index(op.f('ix_b3_prices_ticker'), 'b3_prices', ['ticker'], unique=False)
    op.create_unique_constraint('uq_ticker_trade_date', 'b3_prices', ['ticker', 'trade_date'])
    op.create_index(op.f('ix_ipca_history_id'), 'ipca_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipca_history_id'), table_name='ipca_history')
    op.drop_constraint('uq_ticker_trade_date', 'b3_prices', type_='unique')
    op.drop_index(op.f('ix_b3_prices_ticker'), table_name='b3_prices')
    op.drop_index(op.f('ix_b3_prices_id'), table_name='b3_prices')
    op.create_index(op.f('idx_b3_prices_ticker'), 'b3_prices', ['ticker'], unique=False)
    op.create_index(op.f('b3_prices_ticker_trade_date_uniq'), 'b3_prices', ['ticker', 'trade_date'], unique=True)
    op.create_index(op.f('b3_prices_ticker_trade_date_idx'), 'b3_prices', ['ticker', 'trade_date'], unique=False)
    op.drop_column('b3_prices', 'market_type')
    op.drop_index(op.f('ix_cdi_history_id'), table_name='cdi_history')
    op.drop_table('cdi_history')
    # ### end Alembic commands ###
