"""add adjusted_close to b3_prices

Revision ID: 996774ea844a
Revises: 2e82086b5fe9
Create Date: 2026-01-05 00:39:54.619872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996774ea844a'
down_revision: Union[str, Sequence[str], None] = '2e82086b5fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('b3_prices', sa.Column('adjusted_close', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('b3_prices', 'adjusted_close')
    # ### end Alembic commands ###
