"""Initial tables

Revision ID: df33b7617cc2
Revises: 
Create Date: 2025-12-10 12:34:06.853069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df33b7617cc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('b3_prices', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('b3_prices', 'ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('b3_prices', 'trade_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('b3_prices', 'open',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'high',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'low',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'close',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'volume',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'inserted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('b3_prices_ticker_trade_date_idx'), table_name='b3_prices')
    op.drop_index(op.f('b3_prices_ticker_trade_date_uniq'), table_name='b3_prices')
    op.drop_index(op.f('idx_b3_prices_ticker'), table_name='b3_prices')
    op.create_index(op.f('ix_b3_prices_id'), 'b3_prices', ['id'], unique=False)
    op.create_index(op.f('ix_b3_prices_ticker'), 'b3_prices', ['ticker'], unique=False)
    op.create_unique_constraint('uq_ticker_trade_date', 'b3_prices', ['ticker', 'trade_date'])
    op.drop_column('b3_prices', 'codisi')
    op.drop_column('b3_prices', 'dividend_r$')
    op.drop_column('b3_prices', 'name')
    op.drop_column('b3_prices', 'mes_ano')
    op.drop_column('b3_prices', 'dividend_value')
    op.drop_column('b3_prices', 'dividend_yield_month')
    op.drop_column('b3_prices', 'has_dividend')
    op.drop_column('b3_prices', 'month_ref')
    op.add_column('ifix_history', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('ifix_history', 'trade_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ifix_history', 'close_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_ifix_history_id'), 'ifix_history', ['id'], unique=False)
    op.create_unique_constraint(None, 'ifix_history', ['trade_date'])
    op.drop_column('ifix_history', 'created_at')
    op.alter_column('ipca_history', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ipca_history', 'ipca',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_ipca_history_id'), 'ipca_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipca_history_id'), table_name='ipca_history')
    op.alter_column('ipca_history', 'ipca',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.alter_column('ipca_history', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('ifix_history', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ifix_history', type_='unique')
    op.drop_index(op.f('ix_ifix_history_id'), table_name='ifix_history')
    op.alter_column('ifix_history', 'close_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('ifix_history', 'trade_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('ifix_history', 'id')
    op.add_column('b3_prices', sa.Column('month_ref', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('b3_prices', sa.Column('has_dividend', sa.BOOLEAN(), sa.Computed('("dividend_r$" > (0)::numeric)', persisted=True), autoincrement=False, nullable=True))
    op.add_column('b3_prices', sa.Column('dividend_yield_month', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('b3_prices', sa.Column('dividend_value', sa.NUMERIC(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('b3_prices', sa.Column('mes_ano', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('b3_prices', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('b3_prices', sa.Column('dividend_r$', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('b3_prices', sa.Column('codisi', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_ticker_trade_date', 'b3_prices', type_='unique')
    op.drop_index(op.f('ix_b3_prices_ticker'), table_name='b3_prices')
    op.drop_index(op.f('ix_b3_prices_id'), table_name='b3_prices')
    op.create_index(op.f('idx_b3_prices_ticker'), 'b3_prices', ['ticker'], unique=False)
    op.create_index(op.f('b3_prices_ticker_trade_date_uniq'), 'b3_prices', ['ticker', 'trade_date'], unique=True)
    op.create_index(op.f('b3_prices_ticker_trade_date_idx'), 'b3_prices', ['ticker', 'trade_date'], unique=False)
    op.alter_column('b3_prices', 'inserted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('b3_prices', 'volume',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'close',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'open',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('b3_prices', 'trade_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('b3_prices', 'ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('b3_prices', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
